### ISSUE TITLE
Android Integration - Minified True Issue

### ISSUE THREAD

**Issue by abhi007tyagi** [googleapis/java-dialogflow#181] opened 2020-05-08 20:13 UTC
When integrating inside Android, it works fine when minify=false. for minify=true there is no communication happening with Dialogflow.

Environment details

1. implementation 'com.google.cloud:google-cloud-dialogflow:2.0.0'
    implementation 'io.grpc:grpc-okhttp:1.29.0'
2. OS: 
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.tyagiabhinav.dialogflowchat"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
3. Java version:
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    // Java V2
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/INDEX.LIST'
    }
4. dialogflow version(s):

#### Steps to reproduce

  1. Build a signed APK using https://github.com/abhi007tyagi/DialogflowChat
  2. Send some message to bot
  3. DetectIntentResponse comes NULL

#### Code example
Code: https://github.com/abhi007tyagi/DialogflowChat

in proguard
```
-keepclassmembers class io.grpc.okhttp.OkHttpChannelBuilder {
  io.grpc.okhttp.OkHttpChannelBuilder forTarget(java.lang.String);
  io.grpc.okhttp.OkHttpChannelBuilder scheduledExecutorService(java.util.concurrent.ScheduledExecutorService);
  io.grpc.okhttp.OkHttpChannelBuilder sslSocketFactory(javax.net.ssl.SSLSocketFactory);
  io.grpc.okhttp.OkHttpChannelBuilder transportExecutor(java.util.concurrent.Executor);
}

```

#### Stack trace
No Stack trace. Once this was captured 
```
Conv2Query not enabled due to current app [com.xxxx.yyyy] not in whitelist
```

#### External references such as API reference guides

- https://github.com/abhi007tyagi/DialogflowChat

#### Any additional information below
debug works as minify = false.
release works when minify = false.

**Comment by munkhuushmgl** [comment] 2020-05-18 17:25
@abhi007tyagi I just added to my hotlist, and I will look into this week.

**Comment by gguuss** [comment] 2020-05-19 18:33
Closing because Android is not an officially supported platform, so this is working as intended.

**Closed** 2020-05-19 18:32 UTC
Labels: :rotating_light:, api: dialogflow, triage me

**Comment by abhi007tyagi** [comment] 2020-05-19 18:41
There is actually a lot of demand. Until it is officially supported, is there a workaround for the issue?

**Comment by abhi007tyagi** [comment] 2020-06-18 03:51
@gguuss @munkhuushmgl I have created a [library to add Dialogflow chat into Android](https://medium.com/@abhi007tyagi/android-dialogflow-chatbot-library-6b7b3822e7bc) . I know this is not supported as of now by Google but it may help. Please try at your end :)
